### PR TITLE
Release as a universal wheel

### PR DESCRIPTION
**Pull request by adamchainz**
By releasing as a [Python wheel](http://pythonwheels.com/) as well as a source distribution, you can speed up end user’s installs. After merging this command, to release you just need to run `python setup.py clean sdist bdist_wheel upload`.

### CODE REVIEW

**Comment by techtonik** [comment]
Looks like there is no automation setup for this project, so to make it real, the `bdist_wheel` part should be exposed to people doing the release.

**Comment by adamchainz** [comment]
Bump. Idk who's doing the releases for this.

**Comment by techtonik** [comment]
It seems that the project migrated to https://github.com/python-modernize/python-modernize

**Comment by adamchainz** [comment]
Correct, will have to move my PR there then

**Pull request closed without merging**
